name: ilamb3-dev
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.9
  - numpy
  - xarray
  - pint-xarray
  - cf_xarray
  - pandas
  - intake
  - intake-xarray
  - pytest
  - pytest-cov
  - requests
  - aiohttp
  - jinja2
