name: ilamb3-doc
channels:
  - conda-forge
  - defaults
dependencies:
  - furo
  - numpydoc
  - numpy
  - xarray
  - pint-xarray
  - cf_xarray
  - pandas
  - intake
  - matplotlib
  - pip
  - pip:
      - myst_nb
      - sphinx_autosummary_accessors
      - sphinx_copybutton
      - -e ..
